---
- hosts: localhost
  vars_files:
    - vars.yml
  become: yes

  tasks:
  - name: Create group
    group:
      name: "{{ mm_os_user }}"
      state: present

  - name: Create user
    user: 
      name: "{{ mm_os_user }}"
      group: "{{ mm_os_user }}"

  - name: Prep directories
    file: 
      path: "{{ mm_path }}"
      state: directory
      owner: "{{ mm_os_user }}"
      group: "{{ mm_os_user }}"
